version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: postbox_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: postbox
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      # Das ist der Magic-Trick: Docker führt alle SQL-Dateien in diesem Ordner beim ersten Start aus!
      - ./docker/init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  db_data: